export const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  REFUNDED: 'REFUNDED',
};

export const BOOKING_TYPES = {
  HOTEL: 'HOTEL',
  RESORT: 'RESORT',
  HOMESTAY: 'HOMESTAY',
  TENT: 'TENT',
  GUIDE: 'GUIDE',
  TAXI: 'TAXI',
  HORSE: 'HORSE',
  PRODUCT: 'PRODUCT',
  COMBO: 'COMBO',
  ENQUIRY: 'ENQUIRY',
};

export const GST_RATE = 0.12;

export const REFUND_STATUS = {
  NONE: 'NONE',
  REQUESTED: 'REQUESTED',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
};
