export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  HOTEL_VENDOR: 'HOTEL_VENDOR',
  HOMESTAY_VENDOR: 'HOMESTAY_VENDOR',
  TENT_OPERATOR: 'TENT_OPERATOR',
  GUIDE: 'GUIDE',
  TAXI_OPERATOR: 'TAXI_OPERATOR',
  DRIVER: 'DRIVER',
  HORSE_OPERATOR: 'HORSE_OPERATOR',
  PRODUCT_VENDOR: 'PRODUCT_VENDOR',
  OFFICE_STAFF_HOTEL: 'OFFICE_STAFF_HOTEL',
  OFFICE_STAFF_GUIDE: 'OFFICE_STAFF_GUIDE',
  MARKETING_STAFF: 'MARKETING_STAFF',
  SUPER_ADMIN: 'SUPER_ADMIN',
};

export const VENDOR_ROLES = [
  ROLES.HOTEL_VENDOR,
  ROLES.HOMESTAY_VENDOR,
  ROLES.TENT_OPERATOR,
  ROLES.GUIDE,
  ROLES.TAXI_OPERATOR,
  ROLES.DRIVER,
  ROLES.HORSE_OPERATOR,
  ROLES.PRODUCT_VENDOR,
];

export const STAFF_ROLES = [
  ROLES.OFFICE_STAFF_HOTEL,
  ROLES.OFFICE_STAFF_GUIDE,
  ROLES.MARKETING_STAFF,
];

export const ADMIN_ROLES = [ROLES.SUPER_ADMIN, ...STAFF_ROLES];

export const MARKETING_ROLES = [ROLES.SUPER_ADMIN, ROLES.MARKETING_STAFF];
